name: Keep Render Alive (Daytime Only)

on:
  schedule:
    # Every 5 min from 00:30 UTC (6:00 AM IST) to 17:30 UTC (11:00 PM IST)
    - cron: "*/5 0-17 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check if in allowed time window (IST)
        run: |
          HOUR=$(date -u +"%H")
          MIN=$(date -u +"%M")
          if [ "$HOUR" -eq 0 ] && [ "$MIN" -lt 30 ]; then
            echo "Before 6:00 AM IST — skipping ping."
            exit 0
          fi
          if [ "$HOUR" -eq 17 ] && [ "$MIN" -gt 30 ]; then
            echo "After 11:00 PM IST — skipping ping."
            exit 0
          fi
      - name: Curl the Render service
        run: curl -s -o /dev/null -w "%{http_code}" "${{ secrets.RENDER_URL }}"
